apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configuration
  template:
    metadata:
      labels:
        app: configuration
    spec:
      containers:
        - name: configuration
          image: jmackie17/csc5991:configuration
          ports:
            - containerPort: 80
        imagePullSecrets:
          - name: regcred