apiVersion: v1
kind: Service
metadata:
  name: candidate-service
  labels:
    app: candidate
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: candidate
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP