apiVersion: apps/v1
kind: Deployment
metadata:
  name: security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security
  template:
    metadata:
      labels:
        app: security
    spec:
      containers:
      - name: security
        image: jmackie17/csc5991:security
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred