apiVersion: apps/v1
kind: Deployment
metadata:
  name: securityservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securityservice
  template:
    metadata:
      labels:
        app: securityservice
    spec:
      containers:
      - name: securityservice
        image: jmackie17/csc5991:security
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred