apiVersion: apps/v1
kind: Deployment
metadata:
  name: communications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communications
  template:
    metadata:
      labels:
        app: communications
    spec:
      containers:
      - name: communications
        image: jmackie17/csc5991:communications
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred