apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduling
  template:
    metadata:
      labels:
        app: scheduling
    spec:
      containers:
      - name: scheduling
        image: jmackie17/csc5991:scheduling
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred