apiVersion: v1
kind: Service
metadata:
  name: scheduling-service
  labels:
    app: scheduling
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: scheduling
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP