apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
      - name: employee
        image: jmackie17/csc5991:employee
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred