apiVersion: v1
kind: Service
metadata:
  name: employee-service
  labels:
    app: employee
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: employee
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP