apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: infrastructure-jmackie80
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
      - name: kafka-ui
        image: provectuslabs/kafka-ui
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_CLUSTERS_0_NAME
          value: "kafka"
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          value: "10.152.48.69:9092"