apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
  namespace: infrastructure-jmackie80
  labels:
    app: kafka-ui
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: kafka-ui
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP