apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: infrastructure-jmackie80
  labels:
    app: zookeeper
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
      protocol: TCP
  type: ClusterIP