apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar
  template:
    metadata:
      labels:
        app: calendar
    spec:
      containers:
        - name: calendar
          image: jmackie17/csc5991:calendar
          ports:
            - containerPort: 80
        imagePullSecrets:
          - name: regcred